
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:7.4-node

    steps:
      - checkout

      # Pas besoin de construction dans ce cas, votre application est déjà prête à être déployée
      # Si vous avez des étapes spécifiques à la construction, vous pouvez les ajouter ici.

  deploy:
    docker:
      - image: cimg/ssh:latest

    steps:
      - checkout

      # Clonez le référentiel GitHub où se trouve votre code
      - run:
          name: Clone GitHub repository
          command: git clone git@github.com:sherrypie23/my-web-app.git /opt/lampp/htdocs/mutillidae

      # Déployez l'application sur votre machine virtuelle Azure
      - run:
          name: Deploy to Azure VM
          command: |
            scp -r /opt/lampp/htdocs/mutillidae azureuser@172.211.132.94:/opt/lampp/htdocs
            ssh azureuser@172.211.132.94 "sudo /opt/lampp/xampp restartapache"

# Orchestrez les emplois à l'aide de workflows
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build # Attendre que l'emploi de construction soit terminé avant de déployer
