version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - run:
          name: Download and install sonar-scanner-cli
          command: |
            curl -L -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2568-linux.zip
            unzip sonar-scanner.zip -d /tmp
            export PATH="$PATH:/tmp/sonar-scanner-4.7.0.2568-linux/bin"
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.0

workflows:
  version: 2
  main:
    jobs:
      - build
