version: 2.1
orbs:
  snyk: snyk/snyk@2.1.0
  
jobs:
  snyk_scan:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run: npm ci
      - snyk/scan



workflows:
  main:
    jobs:
      - snyk_scan

