version: 2.1

jobs:
  build:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: Install curl
          command: |
            apt-get update && apt-get install -y curl
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.0

workflows:
  version: 2
  main:
    jobs:
      - build
