version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: php:7.4-cli
    steps:
      - checkout
      # Éventuellement, exécuter des étapes pour installer les dépendances PHP
      - run:
          name: Run PHP unit tests
          command: phpunit
      - sonarcloud/scan

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh azureuser@172.211.132.94 "cd /opt/lampp/htdocs/mutillidae && sudo /opt/lampp/xampp restartapache"

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
