version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.10.0
    steps:
      - checkout
      # Éventuellement, exécutez des étapes pour installer les dépendances de votre projet

  sonarcloud_scan:
    docker:
      - image: cimg/base:2021.09 # Choisissez une image compatible avec SonarCloud
    steps:
      - checkout
      - run:
          name: SonarCloud Scan
          command: sonar-scanner \
            -Dsonar.organization=sherrypie23 \
            -Dsonar.projectKey=sherrypie23_my-web-app \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh azureuser@172.211.132.94 "cd /opt/lampp/htdocs/mutillidae && sudo /opt/lampp/xampp restartapache"

workflows:
  version: 2
  main:
    jobs:
      - build
      - sonarcloud_scan:
          requires:
            - build
      - deploy:
          requires:
            - sonarcloud_scan # Exécuter la tâche de déploiement après l'analyse SonarCloud
            - build
          filters:
            branches:
              only: main
