version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.10.0
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - $AZURE_VM_SSH_FINGERPRINT
      - run:
          name: Copy updated files to VM
          command: scp -o StrictHostKeyChecking=no -r ./* azureuser@172.211.132.94:/opt/lampp/htdocs/mutillidae

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh azureuser@172.211.132.94 "cd /opt/lampp/htdocs/mutillidae && sudo /opt/lampp/xampp restartapache"

  scan:
    working_directory: ~/repo
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    steps:
      - checkout
      - run:
          name: Install OpenJDK
          command: |
            choco install openjdk11 --yes
            refreshenv
      - run:
          name: Download and Install SonarScanner
          command: |
            choco install sonar-scanner-msbuild-net5 --yes
      - run:
          name: Run SonarScanner
          command: |
            sonar-scanner \
              -Dsonar.projectKey=$CIRCLE_BRANCH:$CIRCLE_PROJECT_REPONAME \
              -Dsonar.sources=. \
              -Dsonar.host.url=http://localhost:9099 \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
      - scan:
          context: sonarqube
