version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.10.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Project
          command: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Configure Git
          command: |
            git config --global user.email "ayaelalaoui19@gmail.com"
            git config --global user.name "sherrypie23"
      - run:
          name: Commit and Push Changes
          command: |
            git add .
            git commit -m "Automated build and deploy"
            git push origin main

  sonarcloud_scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: SonarCloud Scan
          command: |
            sonar-scanner \
              -Dsonar.organization=sherrypie23 \
              -Dsonar.projectKey=sherrypie23_my-web-app \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - sonarcloud_scan:
          requires:
            - deploy
