version: 2.1

jobs:
  sonarcloud_scan:
    docker:
      - image: cimg/node:18.10.0
    steps:
      - checkout
      -sonarcloud/scan
orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0  
  workflows:
  main:
  jobs:
      - sonarcloud_scan
