version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  sonarcloud_scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: SonarCloud Scan
          command: sonar-scanner \
            -Dsonar.organization=sherrypie23 \
            -Dsonar.projectKey=sherrypie23_my-web-app \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  main:
    jobs:
      - sonarcloud_scan
