version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.10.0
    steps:
      - checkout
      # Éventuellement, exécutez des étapes pour installer les dépendances de votre projet

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh azureuser@172.211.132.94 "cd /opt/lampp/htdocs/mutillidae && sudo /opt/lampp/xampp restartapache"

  sonarcloud_scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: SonarCloud Scan
          command: sonar-scanner
          Dsonar.login=$SONAR_TOKEN

workflows:
  version: 2
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - sonarcloud_scan:
          requires:
            - deploy
