version: 2.1

orbs:
  snyk: snyk/snyk@2.1.0

jobs:
  snyk_scan:
    docker:
      - image: cimg/php:7.4
    steps:
      - checkout
      - snyk/install
      - snyk/scan

workflows:
  main:
    jobs:
      - snyk_scan
