version: '2.1'

orbs:
  snyk: snyk/snyk@2.1.0  # Assurez-vous de spécifier la version correcte de l'orbe Snyk

jobs:
  build:
    docker:
      - image: cimg/php:7.4
    steps:
      - checkout
      # Éventuellement, d'autres étapes de configuration spécifiques à PHP
      - snyk/scan  # Utilisez le bon nom de la commande pour lancer l'analyse Snyk

workflows:
  main:
    jobs:
      - build
