version: 2.1

jobs:
  synk_scan:
    docker:
      - image: cimg/node:18.10.0
    steps:
      - checkout
      - synk/scan

orbs:
  snyk: snyk/snyk@2.1.0

workflows:
  main:
    jobs:
      - synk_scan
